services:
  - type: web
    name: droob-api
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npx tsx src/server.ts
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: HOST
        value: "0.0.0.0"
      - key: DATABASE_URL
        value: "postgresql://postgres:DyHNJjVhvGySkXgVdgXpaivfxLCOdpru@acela.proxy.rlwy.net:32787/railway"
      - key: REDIS_URL
        value: "redis://default:JFuWlUfUhovizNQLLfmWjGBokHQUJcNX@acela.proxy.rlwy.net:48764"
      - key: JWT_SECRET
        value: "droob-prod-PDRSUVgAwuqELijCyzdktMnfXWZ6ec8b7Km90r2G1sFQ3YNhxopv5O4BTaHlIJ"
      - key: JWT_REFRESH_SECRET
        value: "droob-refresh-u0qClow8VEiPDpOmF72jLhnNdza4txGQ51ZrKW3sU9gYyMcRAfeXb6TBHvJSIk"
      - key: CORS_ORIGIN
        value: "*"
      - key: RATE_LIMIT_MAX
        value: "100"
      - key: DEFAULT_LANGUAGE
        value: "ar"
      - key: TIMEZONE
        value: "Asia/Amman"
      - key: CURRENCY
        value: "JOD"
      - key: FRIDAY_PRAYER_GAP_START
        value: "11:30"
      - key: FRIDAY_PRAYER_GAP_END
        value: "13:30"
      - key: OSRM_BASE_URL
        value: "http://localhost:5000"
      - key: SMTP_HOST
        value: "smtp.gmail.com"
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: "jadjbara10@gmail.com"
      - key: SMTP_PASS
        value: "embvxyxytsbladgw"
      - key: SMTP_FROM
        value: "Droob<noreply@droob.app>"
