/**
 * دروب — Seed: Jordan Transit Terminals (from المجمعات_بالاردن.xlsx)
 * Auto-generated by extract-excel-stops.ts
 * Usage: npx tsx drizzle/seed-terminals.ts
 */
import "dotenv/config";
import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import * as schema from "./schema.js";
import { eq } from "drizzle-orm";

if (!process.env.DATABASE_URL) {
  console.error("❌ DATABASE_URL is required in .env file");
  process.exit(1);
}

const sql = postgres(process.env.DATABASE_URL, { max: 1 });
const db = drizzle(sql, { schema });

const terminalsData = [
  {
    "code": "TM-IR-001",
    "name_ar": "مجمع الشيخ خليل",
    "name_en": "مجمع الشيخ خليل",
    "lat": 32.5567,
    "lng": 35.8433,
    "governorate": "اربد",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-IR-002",
    "name_ar": "المجمع الشمالي",
    "name_en": "المجمع الشمالي",
    "lat": 32.5667,
    "lng": 35.8417,
    "governorate": "اربد",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-IR-003",
    "name_ar": "مجمع خلف التل",
    "name_en": "مجمع خلف التل",
    "lat": 32.55,
    "lng": 35.8583,
    "governorate": "اربد",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-IR-004",
    "name_ar": "مجمع بشرى وسال",
    "name_en": "مجمع بشرى وسال",
    "lat": 32.5333,
    "lng": 35.85,
    "governorate": "اربد",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-IR-005",
    "name_ar": "مجمع الأغوار الجديد",
    "name_en": "مجمع الأغوار الجديد",
    "lat": 32.55,
    "lng": 35.6167,
    "governorate": "اربد",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-IR-006",
    "name_ar": "مجمع عمان الجديد -مجمع الجنوبي-",
    "name_en": "مجمع عمان الجديد -مجمع الجنوبي-",
    "lat": 32.54,
    "lng": 35.8567,
    "governorate": "اربد",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-IR-007",
    "name_ar": "مجمع الأغوار القديم",
    "name_en": "مجمع الأغوار القديم",
    "lat": 32.5467,
    "lng": 35.6167,
    "governorate": "اربد",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-BA-008",
    "name_ar": "مجمع دير علا",
    "name_en": "مجمع دير علا",
    "lat": 32.0667,
    "lng": 35.6,
    "governorate": "البلقاء",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-BA-009",
    "name_ar": "مجمع البقعة",
    "name_en": "مجمع البقعة",
    "lat": 32.0667,
    "lng": 35.85,
    "governorate": "البلقاء",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-BA-010",
    "name_ar": "مجمع السلط الداخلي",
    "name_en": "مجمع السلط الداخلي",
    "lat": 32.0378,
    "lng": 35.7289,
    "governorate": "البلقاء",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-BA-011",
    "name_ar": "مجمع السلط الخارجي",
    "name_en": "مجمع السلط الخارجي",
    "lat": 32.0333,
    "lng": 35.7333,
    "governorate": "البلقاء",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-ZA-012",
    "name_ar": "مجمع الملك عبدالله",
    "name_en": "مجمع الملك عبدالله",
    "lat": 32.085,
    "lng": 36.0967,
    "governorate": "الزرقاء",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-ZA-013",
    "name_ar": "مجمع الأمير راشد",
    "name_en": "مجمع الأمير راشد",
    "lat": 32.0783,
    "lng": 36.1083,
    "governorate": "الزرقاء",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-TA-014",
    "name_ar": "مجمع الطفيلة الخارجي",
    "name_en": "مجمع الطفيلة الخارجي",
    "lat": 30.8389,
    "lng": 35.6056,
    "governorate": "الطفيلة",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-TA-015",
    "name_ar": "مجمع الطفيلة الداخلي",
    "name_en": "مجمع الطفيلة الداخلي",
    "lat": 30.835,
    "lng": 35.6,
    "governorate": "الطفيلة",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-TA-016",
    "name_ar": "مجمع العقبة",
    "name_en": "مجمع العقبة",
    "lat": 29.5317,
    "lng": 35.0061,
    "governorate": "الطفيلة",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-KA-017",
    "name_ar": "مجمع غور المزرعة",
    "name_en": "مجمع غور المزرعة",
    "lat": 31.2833,
    "lng": 35.5167,
    "governorate": "الكرك",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-KA-018",
    "name_ar": "مجمع غور الصافي",
    "name_en": "مجمع غور الصافي",
    "lat": 31.0367,
    "lng": 35.4656,
    "governorate": "الكرك",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-KA-019",
    "name_ar": "مجمع وادي إطوي",
    "name_en": "مجمع وادي إطوي",
    "lat": 31.1833,
    "lng": 35.75,
    "governorate": "الكرك",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-KA-020",
    "name_ar": "مجمع الكرك الجديد",
    "name_en": "مجمع الكرك الجديد",
    "lat": 31.18,
    "lng": 35.705,
    "governorate": "الكرك",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-MF-021",
    "name_ar": "المجمع الغربي",
    "name_en": "المجمع الغربي",
    "lat": 32.3467,
    "lng": 36.1967,
    "governorate": "المفرق",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-MF-022",
    "name_ar": "مجمع جامعة آل البيت",
    "name_en": "مجمع جامعة آل البيت",
    "lat": 32.3667,
    "lng": 36.2333,
    "governorate": "المفرق",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-MF-023",
    "name_ar": "المجمع الشرقي",
    "name_en": "المجمع الشرقي",
    "lat": 32.35,
    "lng": 36.21,
    "governorate": "المفرق",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-JE-024",
    "name_ar": "مجمع جرش الجديد",
    "name_en": "مجمع جرش الجديد",
    "lat": 32.2717,
    "lng": 35.8994,
    "governorate": "جرش",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-AJ-025",
    "name_ar": "مجمع عجلون",
    "name_en": "مجمع عجلون",
    "lat": 32.3325,
    "lng": 35.7517,
    "governorate": "عجلون",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-MD-026",
    "name_ar": "مجمع الشمال-مأدبا",
    "name_en": "مجمع الشمال-مأدبا",
    "lat": 31.72,
    "lng": 35.7933,
    "governorate": "مادبا",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-MD-027",
    "name_ar": "مجمع الجنوب-مأدبا",
    "name_en": "مجمع الجنوب-مأدبا",
    "lat": 31.71,
    "lng": 35.795,
    "governorate": "مادبا",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-MN-028",
    "name_ar": "مجمع جامعة الحسين بن طلال",
    "name_en": "مجمع جامعة الحسين بن طلال",
    "lat": 30.1967,
    "lng": 35.7375,
    "governorate": "معان",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-MN-029",
    "name_ar": "مجمع وادي موسى",
    "name_en": "مجمع وادي موسى",
    "lat": 30.3222,
    "lng": 35.4517,
    "governorate": "معان",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-MN-030",
    "name_ar": "مجمع معان الجديد",
    "name_en": "مجمع معان الجديد",
    "lat": 30.195,
    "lng": 35.73,
    "governorate": "معان",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-AM-031",
    "name_ar": "مجمع رأس العين",
    "name_en": "مجمع رأس العين",
    "lat": 31.9533,
    "lng": 35.9333,
    "governorate": "العاصمة",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-AM-032",
    "name_ar": "مجمع المهاجرين",
    "name_en": "مجمع المهاجرين",
    "lat": 31.9583,
    "lng": 35.9333,
    "governorate": "العاصمة",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-AM-033",
    "name_ar": "مجمع سحاب",
    "name_en": "مجمع سحاب",
    "lat": 31.8667,
    "lng": 36,
    "governorate": "العاصمة",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-AM-034",
    "name_ar": "مجمع صويلح",
    "name_en": "مجمع صويلح",
    "lat": 32.0333,
    "lng": 35.8333,
    "governorate": "العاصمة",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-AM-035",
    "name_ar": "مجمع الشمال - عمان",
    "name_en": "مجمع الشمال - عمان",
    "lat": 32.0167,
    "lng": 35.9167,
    "governorate": "العاصمة",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-AM-036",
    "name_ar": "مجمع رغدان - المحطة",
    "name_en": "مجمع رغدان - المحطة",
    "lat": 31.9539,
    "lng": 35.9153,
    "governorate": "العاصمة",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  },
  {
    "code": "TM-AM-037",
    "name_ar": "مجمع الجنوب الجديد - عمان",
    "name_en": "مجمع الجنوب الجديد - عمان",
    "lat": 31.9167,
    "lng": 35.92,
    "governorate": "العاصمة",
    "is_terminal": true,
    "is_landmark": true,
    "has_shelter": true,
    "has_lighting": true
  }
];

function stableUUID(seed: string): string {
  let hash = 0;
  for (let i = 0; i < seed.length; i++) {
    const char = seed.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash = hash & hash;
  }
  const hex = Math.abs(hash).toString(16).padStart(32, "0").slice(0, 32);
  return `${hex.slice(0,8)}-${hex.slice(8,12)}-${hex.slice(12,16)}-${hex.slice(16,20)}-${hex.slice(20,32)}`;
}

async function seedTerminals() {
  console.log("🚏 زراعة محطات المجمعات من ملف Excel...\n");
  
  let inserted = 0;
  let skipped = 0;

  for (const t of terminalsData) {
    const [existing] = await db.select()
      .from(schema.stops)
      .where(eq(schema.stops.code, t.code))
      .limit(1);
    
    if (existing) {
      console.log(`  ⏭ ${t.name_ar} (${t.code}) - موجودة مسبقاً`);
      skipped++;
      continue;
    }

    await db.insert(schema.stops).values({
      id: stableUUID(`stop-${t.code}`),
      ...t,
    });
    console.log(`  ✓ ${t.name_ar} (${t.code})`);
    inserted++;
  }

  console.log(`\n✅ تمت زراعة المحطات: ${inserted} جديدة, ${skipped} موجودة مسبقاً`);
  console.log(`📍 الإجمالي: ${terminalsData.length} محطة`);
}

seedTerminals()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error("❌ فشلت الزراعة:", err);
    process.exit(1);
  });
